spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ganthas/microservice-config
          repos:
            developper:
              pattern:
                - '*/dev'
              uri: https://github.com/Ganthas/microservice-config2
  application:
    name: config
#HTTP Server
server:
  port: 8888
